spring:
  config:
    import:
      - optional:vault://secret/data/db/booksdb/qa
      - optional:vault://secret/data/keycloak/qa
      - optional:configserver:${CONFIG_SERVER_URL:http://cloud-config-service:9311/config}
