CREATE ROLE bookadmin LOGIN PASSWORD 'bookadmin';
CREATE ROLE theuser LOGIN PASSWORD 'theuser';
GRANT ALL ON SCHEMA public TO bookadmin;
GRANT CONNECT ON DATABASE booksdb TO theuser;
GRANT USAGE ON SCHEMA public TO theuser;
ALTER DEFAULT PRIVILEGES FOR ROLE bookadmin IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO theuser;
