-- Use UUID for primary keys as it's the standard for 16-byte identifiers in PostgreSQL.
-- Use TIMESTAMP for timestamps to not include time zone information.
-- Set default values for created_at and completed fields.
-- Add a foreign key constraint for the author relationship.

CREATE TABLE tbl_authors (
    id UUID NOT NULL PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    genre VARCHAR(255),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP
);

CREATE TABLE tbl_books (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(100) UNIQUE,
    description VARCHAR(100),
    isbn VARCHAR(255),
    publisher VARCHAR(255),
    author_id UUID,
    user_id UUID,
    user_name VARCHAR(20),
    completed BOOLEAN DEFAULT false,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP,
    CONSTRAINT fk_author
        FOREIGN KEY(author_id)
        REFERENCES tbl_authors(id)
);

-- The sequences below are not required if UUIDs are generated by the application.
-- If you need integer-based sequences, this is the correct PostgreSQL syntax.
-- CREATE SEQUENCE author_seq START WITH 1 INCREMENT BY 50;
-- CREATE SEQUENCE book_seq START WITH 1 INCREMENT BY 50;